# coding: utf-8

"""
    System API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import systemv1
from systemv1.models.device_count_by_enrollment_status_model_ import DeviceCountByEnrollmentStatusModel_  # noqa: E501
from systemv1.rest import ApiException


class TestDeviceCountByEnrollmentStatusModel_(unittest.TestCase):
    """DeviceCountByEnrollmentStatusModel_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceCountByEnrollmentStatusModel_(self):
        """Test DeviceCountByEnrollmentStatusModel_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = systemv1.models.device_count_by_enrollment_status_model_.DeviceCountByEnrollmentStatusModel_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
