# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mdmv1.configuration import Configuration


class FailedBulkUpdateDeviceResponseV1Model(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'serial_number': 'str',
        'user_name': 'str',
        'error_code': 'int',
        'message': 'str',
        'failed_custom_attributes': 'list[FailedBulkUpdateDeviceCustomAttributeResponseV1Model]',
        'id': 'int',
        'uuid': 'str'
    }

    attribute_map = {
        'serial_number': 'serialNumber',
        'user_name': 'userName',
        'error_code': 'errorCode',
        'message': 'message',
        'failed_custom_attributes': 'failedCustomAttributes',
        'id': 'id',
        'uuid': 'uuid'
    }

    def __init__(self, serial_number=None, user_name=None, error_code=None, message=None, failed_custom_attributes=None, id=None, uuid=None, _configuration=None):  # noqa: E501
        """FailedBulkUpdateDeviceResponseV1Model - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._serial_number = None
        self._user_name = None
        self._error_code = None
        self._message = None
        self._failed_custom_attributes = None
        self._id = None
        self._uuid = None
        self.discriminator = None

        self.serial_number = serial_number
        self.user_name = user_name
        self.error_code = error_code
        self.message = message
        if failed_custom_attributes is not None:
            self.failed_custom_attributes = failed_custom_attributes
        if id is not None:
            self.id = id
        if uuid is not None:
            self.uuid = uuid

    @property
    def serial_number(self):
        """Gets the serial_number of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Serial Number of the device  # noqa: E501

        :return: The serial_number of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this FailedBulkUpdateDeviceResponseV1Model.

        Serial Number of the device  # noqa: E501

        :param serial_number: The serial_number of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def user_name(self):
        """Gets the user_name of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Enrollment user name  # noqa: E501

        :return: The user_name of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this FailedBulkUpdateDeviceResponseV1Model.

        Enrollment user name  # noqa: E501

        :param user_name: The user_name of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    @property
    def error_code(self):
        """Gets the error_code of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Error code for the failure  # noqa: E501

        :return: The error_code of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this FailedBulkUpdateDeviceResponseV1Model.

        Error code for the failure  # noqa: E501

        :param error_code: The error_code of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def message(self):
        """Gets the message of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        The error message  # noqa: E501

        :return: The message of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this FailedBulkUpdateDeviceResponseV1Model.

        The error message  # noqa: E501

        :param message: The message of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def failed_custom_attributes(self):
        """Gets the failed_custom_attributes of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Collection of failed custom attributes for the device.  # noqa: E501

        :return: The failed_custom_attributes of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: list[FailedBulkUpdateDeviceCustomAttributeResponseV1Model]
        """
        return self._failed_custom_attributes

    @failed_custom_attributes.setter
    def failed_custom_attributes(self, failed_custom_attributes):
        """Sets the failed_custom_attributes of this FailedBulkUpdateDeviceResponseV1Model.

        Collection of failed custom attributes for the device.  # noqa: E501

        :param failed_custom_attributes: The failed_custom_attributes of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: list[FailedBulkUpdateDeviceCustomAttributeResponseV1Model]
        """

        self._failed_custom_attributes = failed_custom_attributes

    @property
    def id(self):
        """Gets the id of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Gets or sets identifier.  # noqa: E501

        :return: The id of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FailedBulkUpdateDeviceResponseV1Model.

        Gets or sets identifier.  # noqa: E501

        :param id: The id of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def uuid(self):
        """Gets the uuid of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501

        Gets or sets current objects UUID.  # noqa: E501

        :return: The uuid of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this FailedBulkUpdateDeviceResponseV1Model.

        Gets or sets current objects UUID.  # noqa: E501

        :param uuid: The uuid of this FailedBulkUpdateDeviceResponseV1Model.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FailedBulkUpdateDeviceResponseV1Model, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FailedBulkUpdateDeviceResponseV1Model):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FailedBulkUpdateDeviceResponseV1Model):
            return True

        return self.to_dict() != other.to_dict()
