# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mdmv1.configuration import Configuration


class GenericMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message_body': 'str',
        'message_type': 'str',
        'application_name': 'str'
    }

    attribute_map = {
        'message_body': 'MessageBody',
        'message_type': 'MessageType',
        'application_name': 'ApplicationName'
    }

    def __init__(self, message_body=None, message_type=None, application_name=None, _configuration=None):  # noqa: E501
        """GenericMessage - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._message_body = None
        self._message_type = None
        self._application_name = None
        self.discriminator = None

        if message_body is not None:
            self.message_body = message_body
        if message_type is not None:
            self.message_type = message_type
        if application_name is not None:
            self.application_name = application_name

    @property
    def message_body(self):
        """Gets the message_body of this GenericMessage.  # noqa: E501

        Gets or sets message Body.  # noqa: E501

        :return: The message_body of this GenericMessage.  # noqa: E501
        :rtype: str
        """
        return self._message_body

    @message_body.setter
    def message_body(self, message_body):
        """Sets the message_body of this GenericMessage.

        Gets or sets message Body.  # noqa: E501

        :param message_body: The message_body of this GenericMessage.  # noqa: E501
        :type: str
        """

        self._message_body = message_body

    @property
    def message_type(self):
        """Gets the message_type of this GenericMessage.  # noqa: E501

        Gets or sets the type of message.  # noqa: E501

        :return: The message_type of this GenericMessage.  # noqa: E501
        :rtype: str
        """
        return self._message_type

    @message_type.setter
    def message_type(self, message_type):
        """Sets the message_type of this GenericMessage.

        Gets or sets the type of message.  # noqa: E501

        :param message_type: The message_type of this GenericMessage.  # noqa: E501
        :type: str
        """

        self._message_type = message_type

    @property
    def application_name(self):
        """Gets the application_name of this GenericMessage.  # noqa: E501

        Gets or sets application Name.  # noqa: E501

        :return: The application_name of this GenericMessage.  # noqa: E501
        :rtype: str
        """
        return self._application_name

    @application_name.setter
    def application_name(self, application_name):
        """Sets the application_name of this GenericMessage.

        Gets or sets application Name.  # noqa: E501

        :param application_name: The application_name of this GenericMessage.  # noqa: E501
        :type: str
        """

        self._application_name = application_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GenericMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericMessage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenericMessage):
            return True

        return self.to_dict() != other.to_dict()
