# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mdmv1.configuration import Configuration


class OperatorTypeMapModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'og_uuid': 'str',
        'operator_type_map': 'OperatorTypeMap'
    }

    attribute_map = {
        'og_uuid': 'og_uuid',
        'operator_type_map': 'operator_type_map'
    }

    def __init__(self, og_uuid=None, operator_type_map=None, _configuration=None):  # noqa: E501
        """OperatorTypeMapModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._og_uuid = None
        self._operator_type_map = None
        self.discriminator = None

        if og_uuid is not None:
            self.og_uuid = og_uuid
        if operator_type_map is not None:
            self.operator_type_map = operator_type_map

    @property
    def og_uuid(self):
        """Gets the og_uuid of this OperatorTypeMapModel.  # noqa: E501

        The Organization Group UUID.  # noqa: E501

        :return: The og_uuid of this OperatorTypeMapModel.  # noqa: E501
        :rtype: str
        """
        return self._og_uuid

    @og_uuid.setter
    def og_uuid(self, og_uuid):
        """Sets the og_uuid of this OperatorTypeMapModel.

        The Organization Group UUID.  # noqa: E501

        :param og_uuid: The og_uuid of this OperatorTypeMapModel.  # noqa: E501
        :type: str
        """

        self._og_uuid = og_uuid

    @property
    def operator_type_map(self):
        """Gets the operator_type_map of this OperatorTypeMapModel.  # noqa: E501

        The operator-type map for a particular type.  # noqa: E501

        :return: The operator_type_map of this OperatorTypeMapModel.  # noqa: E501
        :rtype: OperatorTypeMap
        """
        return self._operator_type_map

    @operator_type_map.setter
    def operator_type_map(self, operator_type_map):
        """Sets the operator_type_map of this OperatorTypeMapModel.

        The operator-type map for a particular type.  # noqa: E501

        :param operator_type_map: The operator_type_map of this OperatorTypeMapModel.  # noqa: E501
        :type: OperatorTypeMap
        """

        self._operator_type_map = operator_type_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OperatorTypeMapModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OperatorTypeMapModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OperatorTypeMapModel):
            return True

        return self.to_dict() != other.to_dict()
