# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from mdmv1.configuration import Configuration


class ProductComplianceIssueSummaryDetailsV1Model(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_compliance_status_id': 'int',
        'product_compliance_status': 'str',
        'compliance_status_count': 'int'
    }

    attribute_map = {
        'product_compliance_status_id': 'ProductComplianceStatusId',
        'product_compliance_status': 'ProductComplianceStatus',
        'compliance_status_count': 'ComplianceStatusCount'
    }

    def __init__(self, product_compliance_status_id=None, product_compliance_status=None, compliance_status_count=None, _configuration=None):  # noqa: E501
        """ProductComplianceIssueSummaryDetailsV1Model - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._product_compliance_status_id = None
        self._product_compliance_status = None
        self._compliance_status_count = None
        self.discriminator = None

        if product_compliance_status_id is not None:
            self.product_compliance_status_id = product_compliance_status_id
        if product_compliance_status is not None:
            self.product_compliance_status = product_compliance_status
        if compliance_status_count is not None:
            self.compliance_status_count = compliance_status_count

    @property
    def product_compliance_status_id(self):
        """Gets the product_compliance_status_id of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501

        Gets or sets product compliance status id.  # noqa: E501

        :return: The product_compliance_status_id of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :rtype: int
        """
        return self._product_compliance_status_id

    @product_compliance_status_id.setter
    def product_compliance_status_id(self, product_compliance_status_id):
        """Sets the product_compliance_status_id of this ProductComplianceIssueSummaryDetailsV1Model.

        Gets or sets product compliance status id.  # noqa: E501

        :param product_compliance_status_id: The product_compliance_status_id of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :type: int
        """

        self._product_compliance_status_id = product_compliance_status_id

    @property
    def product_compliance_status(self):
        """Gets the product_compliance_status of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501

        Gets or sets Product compliance status Name.  # noqa: E501

        :return: The product_compliance_status of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :rtype: str
        """
        return self._product_compliance_status

    @product_compliance_status.setter
    def product_compliance_status(self, product_compliance_status):
        """Sets the product_compliance_status of this ProductComplianceIssueSummaryDetailsV1Model.

        Gets or sets Product compliance status Name.  # noqa: E501

        :param product_compliance_status: The product_compliance_status of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :type: str
        """

        self._product_compliance_status = product_compliance_status

    @property
    def compliance_status_count(self):
        """Gets the compliance_status_count of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501

        Gets or sets the Compliance Status Count.  # noqa: E501

        :return: The compliance_status_count of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :rtype: int
        """
        return self._compliance_status_count

    @compliance_status_count.setter
    def compliance_status_count(self, compliance_status_count):
        """Sets the compliance_status_count of this ProductComplianceIssueSummaryDetailsV1Model.

        Gets or sets the Compliance Status Count.  # noqa: E501

        :param compliance_status_count: The compliance_status_count of this ProductComplianceIssueSummaryDetailsV1Model.  # noqa: E501
        :type: int
        """

        self._compliance_status_count = compliance_status_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductComplianceIssueSummaryDetailsV1Model, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductComplianceIssueSummaryDetailsV1Model):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProductComplianceIssueSummaryDetailsV1Model):
            return True

        return self.to_dict() != other.to_dict()
