# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.models.apple_tv_conference_mode_payload_v2_entity import AppleTvConferenceModePayloadV2Entity  # noqa: E501
from mdmv2.rest import ApiException


class TestAppleTvConferenceModePayloadV2Entity(unittest.TestCase):
    """AppleTvConferenceModePayloadV2Entity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppleTvConferenceModePayloadV2Entity(self):
        """Test AppleTvConferenceModePayloadV2Entity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv2.models.apple_tv_conference_mode_payload_v2_entity.AppleTvConferenceModePayloadV2Entity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
