# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.models.android_wifi_payload_v2_entity import AndroidWifiPayloadV2Entity  # noqa: E501
from mdmv2.rest import ApiException


class TestAndroidWifiPayloadV2Entity(unittest.TestCase):
    """AndroidWifiPayloadV2Entity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAndroidWifiPayloadV2Entity(self):
        """Test AndroidWifiPayloadV2Entity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv2.models.android_wifi_payload_v2_entity.AndroidWifiPayloadV2Entity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
