# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.models.android_for_work_auto_update_payload_v2_entity_ import AndroidForWorkAutoUpdatePayloadV2Entity_  # noqa: E501
from mdmv2.rest import ApiException


class TestAndroidForWorkAutoUpdatePayloadV2Entity_(unittest.TestCase):
    """AndroidForWorkAutoUpdatePayloadV2Entity_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAndroidForWorkAutoUpdatePayloadV2Entity_(self):
        """Test AndroidForWorkAutoUpdatePayloadV2Entity_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv2.models.android_for_work_auto_update_payload_v2_entity_.AndroidForWorkAutoUpdatePayloadV2Entity_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
