# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.models.apple_os_x_eas_microsoft_outlook_payload_entity import AppleOsXEasMicrosoftOutlookPayloadEntity  # noqa: E501
from mdmv2.rest import ApiException


class TestAppleOsXEasMicrosoftOutlookPayloadEntity(unittest.TestCase):
    """AppleOsXEasMicrosoftOutlookPayloadEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppleOsXEasMicrosoftOutlookPayloadEntity(self):
        """Test AppleOsXEasMicrosoftOutlookPayloadEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv2.models.apple_os_x_eas_microsoft_outlook_payload_entity.AppleOsXEasMicrosoftOutlookPayloadEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
