# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.api.remote_management_v2_api import RemoteManagementV2Api  # noqa: E501
from mdmv2.rest import ApiException


class TestRemoteManagementV2Api(unittest.TestCase):
    """RemoteManagementV2Api unit test stubs"""

    def setUp(self):
        self.api = mdmv2.api.remote_management_v2_api.RemoteManagementV2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_remote_management_v2_initiate_rm_session_async(self):
        """Test case for remote_management_v2_initiate_rm_session_async

        New - Initiates a Remote Management session.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
