# coding: utf-8

"""
    MDM API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv2
from mdmv2.models.mac_os_allowed_kernel_extensions_entity_ import MacOsAllowedKernelExtensionsEntity_  # noqa: E501
from mdmv2.rest import ApiException


class TestMacOsAllowedKernelExtensionsEntity_(unittest.TestCase):
    """MacOsAllowedKernelExtensionsEntity_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMacOsAllowedKernelExtensionsEntity_(self):
        """Test MacOsAllowedKernelExtensionsEntity_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv2.models.mac_os_allowed_kernel_extensions_entity_.MacOsAllowedKernelExtensionsEntity_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
