# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv1
from mdmv1.models.product_set_inquiry_response_model import ProductSetInquiryResponseModel  # noqa: E501
from mdmv1.rest import ApiException


class TestProductSetInquiryResponseModel(unittest.TestCase):
    """ProductSetInquiryResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductSetInquiryResponseModel(self):
        """Test ProductSetInquiryResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv1.models.product_set_inquiry_response_model.ProductSetInquiryResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
