# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv1
from mdmv1.models.oem_update_installed_device_info_v1_model import OemUpdateInstalledDeviceInfoV1Model  # noqa: E501
from mdmv1.rest import ApiException


class TestOemUpdateInstalledDeviceInfoV1Model(unittest.TestCase):
    """OemUpdateInstalledDeviceInfoV1Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOemUpdateInstalledDeviceInfoV1Model(self):
        """Test OemUpdateInstalledDeviceInfoV1Model"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv1.models.oem_update_installed_device_info_v1_model.OemUpdateInstalledDeviceInfoV1Model()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
