# coding: utf-8

"""
    MDM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv1
from mdmv1.models.tunnel_server_certificate_config_v1_model import TunnelServerCertificateConfigV1Model  # noqa: E501
from mdmv1.rest import ApiException


class TestTunnelServerCertificateConfigV1Model(unittest.TestCase):
    """TunnelServerCertificateConfigV1Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTunnelServerCertificateConfigV1Model(self):
        """Test TunnelServerCertificateConfigV1Model"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv1.models.tunnel_server_certificate_config_v1_model.TunnelServerCertificateConfigV1Model()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
