# coding: utf-8

"""
    MDM API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv3
from mdmv3.models.base_exception_model import BaseExceptionModel  # noqa: E501
from mdmv3.rest import ApiException


class TestBaseExceptionModel(unittest.TestCase):
    """BaseExceptionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseExceptionModel(self):
        """Test BaseExceptionModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv3.models.base_exception_model.BaseExceptionModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
