# coding: utf-8

"""
    MDM API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mdmv3
from mdmv3.models.request_query import RequestQuery  # noqa: E501
from mdmv3.rest import ApiException


class TestRequestQuery(unittest.TestCase):
    """RequestQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestQuery(self):
        """Test RequestQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mdmv3.models.request_query.RequestQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
