from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from mdmv1.api.admin_action_v1_api import AdminActionV1Api
from mdmv1.api.apple_v1_api import AppleV1Api
from mdmv1.api.apps_api import AppsApi
from mdmv1.api.apps_v1_api import AppsV1Api
from mdmv1.api.assignment_groups_v1_api import AssignmentGroupsV1Api
from mdmv1.api.bit_locker_v1_api import BitLockerV1Api
from mdmv1.api.catalogs_v1_api import CatalogsV1Api
from mdmv1.api.certificates_api import CertificatesApi
from mdmv1.api.chrome_os_v1_api import ChromeOsV1Api
from mdmv1.api.commands_v1_api import CommandsV1Api
from mdmv1.api.compliance_policy_v1_api import CompliancePolicyV1Api
from mdmv1.api.compliance_v1_api import ComplianceV1Api
from mdmv1.api.contents_api import ContentsApi
from mdmv1.api.device_attributes_v1_api import DeviceAttributesV1Api
from mdmv1.api.device_custom_attributes_api import DeviceCustomAttributesApi
from mdmv1.api.device_enrollment_program_v1_api import DeviceEnrollmentProgramV1Api
from mdmv1.api.device_log_v1_api import DeviceLogV1Api
from mdmv1.api.device_lookups_v1_api import DeviceLookupsV1Api
from mdmv1.api.device_samples_api import DeviceSamplesApi
from mdmv1.api.device_sensors_api import DeviceSensorsApi
from mdmv1.api.device_sensors_v1_api import DeviceSensorsV1Api
from mdmv1.api.device_smart_groups_api import DeviceSmartGroupsApi
from mdmv1.api.device_state_metadata_v1_api import DeviceStateMetadataV1Api
from mdmv1.api.devices_api import DevicesApi
from mdmv1.api.direct_enrollment_settings_v1_api import DirectEnrollmentSettingsV1Api
from mdmv1.api.dropship_provisioning_actions_v1_api import DropshipProvisioningActionsV1Api
from mdmv1.api.dsm_v1_api import DsmV1Api
from mdmv1.api.enrollment_token_v1_api import EnrollmentTokenV1Api
from mdmv1.api.event_log_api import EventLogApi
from mdmv1.api.gps_api import GPSApi
from mdmv1.api.hub_agent_packages_v1_api import HubAgentPackagesV1Api
from mdmv1.api.messages_api import MessagesApi
from mdmv1.api.network_api import NetworkApi
from mdmv1.api.notes_api import NotesApi
from mdmv1.api.ops_device_last_sync_details_api import OPSDeviceLastSyncDetailsApi
from mdmv1.api.os_versions_v1_api import OSVersionsV1Api
from mdmv1.api.oem_enrollment_token_v1_api import OemEnrollmentTokenV1Api
from mdmv1.api.oem_updates_search_v1_api import OemUpdatesSearchV1Api
from mdmv1.api.oem_updates_v1_api import OemUpdatesV1Api
from mdmv1.api.operator_type_map_v1_api import OperatorTypeMapV1Api
from mdmv1.api.peripherals_api import PeripheralsApi
from mdmv1.api.pick_lists_api import PickListsApi
from mdmv1.api.policies_v1_api import PoliciesV1Api
from mdmv1.api.product_components_v1_api import ProductComponentsV1Api
from mdmv1.api.product_set_v1_api import ProductSetV1Api
from mdmv1.api.products_v1_api import ProductsV1Api
from mdmv1.api.profiles_api import ProfilesApi
from mdmv1.api.profiles_v1_api import ProfilesV1Api
from mdmv1.api.registration_v1_api import RegistrationV1Api
from mdmv1.api.relay_servers_v1_api import RelayServersV1Api
from mdmv1.api.remote_management_v1_api import RemoteManagementV1Api
from mdmv1.api.resource_action_v1_api import ResourceActionV1Api
from mdmv1.api.resources_v1_api import ResourcesV1Api
from mdmv1.api.script_assignment_v1_api import ScriptAssignmentV1Api
from mdmv1.api.scripts_v1_api import ScriptsV1Api
from mdmv1.api.security_v1_api import SecurityV1Api
from mdmv1.api.smart_groups_api import SmartGroupsApi
from mdmv1.api.staging_bundles_v1_api import StagingBundlesV1Api
from mdmv1.api.staging_bundles_v2_api import StagingBundlesV2Api
from mdmv1.api.staging_v1_api import StagingV1Api
from mdmv1.api.tags_api import TagsApi
from mdmv1.api.telecom_devices_api import TelecomDevicesApi
from mdmv1.api.templates_v1_api import TemplatesV1Api
from mdmv1.api.tunnel_admin_action_v1_api import TunnelAdminActionV1Api
from mdmv1.api.tunnel_device_v1_api import TunnelDeviceV1Api
from mdmv1.api.tunnel_health_v1_api import TunnelHealthV1Api
from mdmv1.api.tunnel_standalone_client_v1_api import TunnelStandaloneClientV1Api
from mdmv1.api.updates_v1_api import UpdatesV1Api
from mdmv1.api.users_api import UsersApi
from mdmv1.api.workflow_default_range_v1_api import WorkflowDefaultRangeV1Api
from mdmv1.api.workflow_device_side_v1_api import WorkflowDeviceSideV1Api
from mdmv1.api.workflow_entity_v1_api import WorkflowEntityV1Api
from mdmv1.api.workflow_status_reporting_api import WorkflowStatusReportingApi
from mdmv1.api.workflow_status_summary_v1_api import WorkflowStatusSummaryV1Api
from mdmv1.api.workflow_v1_api import WorkflowV1Api
