# coding: utf-8

"""
    MAM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mamv1
from mamv1.models.mac_os_edit_application_request_v1_model import MacOsEditApplicationRequestV1Model  # noqa: E501
from mamv1.rest import ApiException


class TestMacOsEditApplicationRequestV1Model(unittest.TestCase):
    """MacOsEditApplicationRequestV1Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMacOsEditApplicationRequestV1Model(self):
        """Test MacOsEditApplicationRequestV1Model"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mamv1.models.mac_os_edit_application_request_v1_model.MacOsEditApplicationRequestV1Model()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
