# coding: utf-8

"""
    MAM API V1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mamv1
from mamv1.models.msi_deployment_param_model_ import MsiDeploymentParamModel_  # noqa: E501
from mamv1.rest import ApiException


class TestMsiDeploymentParamModel_(unittest.TestCase):
    """MsiDeploymentParamModel_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMsiDeploymentParamModel_(self):
        """Test MsiDeploymentParamModel_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mamv1.models.msi_deployment_param_model_.MsiDeploymentParamModel_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
