# coding: utf-8

"""
    System API V2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from systemv2.configuration import Configuration


class AdminV2Model(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'password': 'str',
        'first_name': 'str',
        'last_name': 'str',
        'email': 'str',
        'time_zone': 'str',
        'locale': 'str',
        'initial_landing_page': 'str',
        'is_active_directory_user': 'bool',
        'requires_password_change': 'bool',
        'roles': 'list[RoleV2Model]',
        'message_template_id': 'int',
        'message_template_uuid': 'str',
        'message_type': 'int',
        'v_idm_elevation_status': 'int',
        'organization_group_id': 'int',
        'organization_group_uuid': 'str',
        'id': 'int',
        'uuid': 'str'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'first_name': 'firstName',
        'last_name': 'lastName',
        'email': 'email',
        'time_zone': 'timeZone',
        'locale': 'locale',
        'initial_landing_page': 'initialLandingPage',
        'is_active_directory_user': 'isActiveDirectoryUser',
        'requires_password_change': 'requiresPasswordChange',
        'roles': 'roles',
        'message_template_id': 'messageTemplateId',
        'message_template_uuid': 'messageTemplateUuid',
        'message_type': 'messageType',
        'v_idm_elevation_status': 'vIDMElevationStatus',
        'organization_group_id': 'organizationGroupId',
        'organization_group_uuid': 'organizationGroupUuid',
        'id': 'id',
        'uuid': 'uuid'
    }

    def __init__(self, username=None, password=None, first_name=None, last_name=None, email=None, time_zone=None, locale=None, initial_landing_page=None, is_active_directory_user=None, requires_password_change=None, roles=None, message_template_id=None, message_template_uuid=None, message_type=None, v_idm_elevation_status=None, organization_group_id=None, organization_group_uuid=None, id=None, uuid=None, _configuration=None):  # noqa: E501
        """AdminV2Model - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._username = None
        self._password = None
        self._first_name = None
        self._last_name = None
        self._email = None
        self._time_zone = None
        self._locale = None
        self._initial_landing_page = None
        self._is_active_directory_user = None
        self._requires_password_change = None
        self._roles = None
        self._message_template_id = None
        self._message_template_uuid = None
        self._message_type = None
        self._v_idm_elevation_status = None
        self._organization_group_id = None
        self._organization_group_uuid = None
        self._id = None
        self._uuid = None
        self.discriminator = None

        if username is not None:
            self.username = username
        if password is not None:
            self.password = password
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name
        if email is not None:
            self.email = email
        if time_zone is not None:
            self.time_zone = time_zone
        if locale is not None:
            self.locale = locale
        if initial_landing_page is not None:
            self.initial_landing_page = initial_landing_page
        if is_active_directory_user is not None:
            self.is_active_directory_user = is_active_directory_user
        if requires_password_change is not None:
            self.requires_password_change = requires_password_change
        if roles is not None:
            self.roles = roles
        if message_template_id is not None:
            self.message_template_id = message_template_id
        if message_template_uuid is not None:
            self.message_template_uuid = message_template_uuid
        if message_type is not None:
            self.message_type = message_type
        if v_idm_elevation_status is not None:
            self.v_idm_elevation_status = v_idm_elevation_status
        if organization_group_id is not None:
            self.organization_group_id = organization_group_id
        if organization_group_uuid is not None:
            self.organization_group_uuid = organization_group_uuid
        if id is not None:
            self.id = id
        if uuid is not None:
            self.uuid = uuid

    @property
    def username(self):
        """Gets the username of this AdminV2Model.  # noqa: E501

        Gets or sets name of the admin user.  # noqa: E501

        :return: The username of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AdminV2Model.

        Gets or sets name of the admin user.  # noqa: E501

        :param username: The username of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this AdminV2Model.  # noqa: E501

        Gets or sets password of the admin user.  # noqa: E501

        :return: The password of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AdminV2Model.

        Gets or sets password of the admin user.  # noqa: E501

        :param password: The password of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def first_name(self):
        """Gets the first_name of this AdminV2Model.  # noqa: E501

        Gets or sets firstName of the admin user.  # noqa: E501

        :return: The first_name of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this AdminV2Model.

        Gets or sets firstName of the admin user.  # noqa: E501

        :param first_name: The first_name of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this AdminV2Model.  # noqa: E501

        Gets or sets lastName of the admin user.  # noqa: E501

        :return: The last_name of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this AdminV2Model.

        Gets or sets lastName of the admin user.  # noqa: E501

        :param last_name: The last_name of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this AdminV2Model.  # noqa: E501

        Gets or sets email address of the admin user.  # noqa: E501

        :return: The email of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AdminV2Model.

        Gets or sets email address of the admin user.  # noqa: E501

        :param email: The email of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def time_zone(self):
        """Gets the time_zone of this AdminV2Model.  # noqa: E501

        Gets or sets time zone.  # noqa: E501

        :return: The time_zone of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone):
        """Sets the time_zone of this AdminV2Model.

        Gets or sets time zone.  # noqa: E501

        :param time_zone: The time_zone of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._time_zone = time_zone

    @property
    def locale(self):
        """Gets the locale of this AdminV2Model.  # noqa: E501

        Gets or sets culture code.  # noqa: E501

        :return: The locale of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this AdminV2Model.

        Gets or sets culture code.  # noqa: E501

        :param locale: The locale of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def initial_landing_page(self):
        """Gets the initial_landing_page of this AdminV2Model.  # noqa: E501

        Gets or sets initial landing page of AirWatch console.  # noqa: E501

        :return: The initial_landing_page of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._initial_landing_page

    @initial_landing_page.setter
    def initial_landing_page(self, initial_landing_page):
        """Sets the initial_landing_page of this AdminV2Model.

        Gets or sets initial landing page of AirWatch console.  # noqa: E501

        :param initial_landing_page: The initial_landing_page of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._initial_landing_page = initial_landing_page

    @property
    def is_active_directory_user(self):
        """Gets the is_active_directory_user of this AdminV2Model.  # noqa: E501

        Gets or sets a value indicating whether flag to indicate whether the admin user is LDAP/AD user.  # noqa: E501

        :return: The is_active_directory_user of this AdminV2Model.  # noqa: E501
        :rtype: bool
        """
        return self._is_active_directory_user

    @is_active_directory_user.setter
    def is_active_directory_user(self, is_active_directory_user):
        """Sets the is_active_directory_user of this AdminV2Model.

        Gets or sets a value indicating whether flag to indicate whether the admin user is LDAP/AD user.  # noqa: E501

        :param is_active_directory_user: The is_active_directory_user of this AdminV2Model.  # noqa: E501
        :type: bool
        """

        self._is_active_directory_user = is_active_directory_user

    @property
    def requires_password_change(self):
        """Gets the requires_password_change of this AdminV2Model.  # noqa: E501

        Gets or sets a value indicating whether flag to indicate whether the admin user requires to change the password on next login.  # noqa: E501

        :return: The requires_password_change of this AdminV2Model.  # noqa: E501
        :rtype: bool
        """
        return self._requires_password_change

    @requires_password_change.setter
    def requires_password_change(self, requires_password_change):
        """Sets the requires_password_change of this AdminV2Model.

        Gets or sets a value indicating whether flag to indicate whether the admin user requires to change the password on next login.  # noqa: E501

        :param requires_password_change: The requires_password_change of this AdminV2Model.  # noqa: E501
        :type: bool
        """

        self._requires_password_change = requires_password_change

    @property
    def roles(self):
        """Gets the roles of this AdminV2Model.  # noqa: E501

        Gets or sets roles associated with the admin user.  # noqa: E501

        :return: The roles of this AdminV2Model.  # noqa: E501
        :rtype: list[RoleV2Model]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this AdminV2Model.

        Gets or sets roles associated with the admin user.  # noqa: E501

        :param roles: The roles of this AdminV2Model.  # noqa: E501
        :type: list[RoleV2Model]
        """

        self._roles = roles

    @property
    def message_template_id(self):
        """Gets the message_template_id of this AdminV2Model.  # noqa: E501

        Gets or sets message template ID.  # noqa: E501

        :return: The message_template_id of this AdminV2Model.  # noqa: E501
        :rtype: int
        """
        return self._message_template_id

    @message_template_id.setter
    def message_template_id(self, message_template_id):
        """Sets the message_template_id of this AdminV2Model.

        Gets or sets message template ID.  # noqa: E501

        :param message_template_id: The message_template_id of this AdminV2Model.  # noqa: E501
        :type: int
        """

        self._message_template_id = message_template_id

    @property
    def message_template_uuid(self):
        """Gets the message_template_uuid of this AdminV2Model.  # noqa: E501

        Gets or sets message template UUID.  # noqa: E501

        :return: The message_template_uuid of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._message_template_uuid

    @message_template_uuid.setter
    def message_template_uuid(self, message_template_uuid):
        """Sets the message_template_uuid of this AdminV2Model.

        Gets or sets message template UUID.  # noqa: E501

        :param message_template_uuid: The message_template_uuid of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._message_template_uuid = message_template_uuid

    @property
    def message_type(self):
        """Gets the message_type of this AdminV2Model.  # noqa: E501

        Gets or sets message type.  # noqa: E501

        :return: The message_type of this AdminV2Model.  # noqa: E501
        :rtype: int
        """
        return self._message_type

    @message_type.setter
    def message_type(self, message_type):
        """Sets the message_type of this AdminV2Model.

        Gets or sets message type.  # noqa: E501

        :param message_type: The message_type of this AdminV2Model.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]  # noqa: E501
        if (self._configuration.client_side_validation and
                message_type not in allowed_values):
            raise ValueError(
                "Invalid value for `message_type` ({0}), must be one of {1}"  # noqa: E501
                .format(message_type, allowed_values)
            )

        self._message_type = message_type

    @property
    def v_idm_elevation_status(self):
        """Gets the v_idm_elevation_status of this AdminV2Model.  # noqa: E501

        Gets or sets elevation status.  # noqa: E501

        :return: The v_idm_elevation_status of this AdminV2Model.  # noqa: E501
        :rtype: int
        """
        return self._v_idm_elevation_status

    @v_idm_elevation_status.setter
    def v_idm_elevation_status(self, v_idm_elevation_status):
        """Sets the v_idm_elevation_status of this AdminV2Model.

        Gets or sets elevation status.  # noqa: E501

        :param v_idm_elevation_status: The v_idm_elevation_status of this AdminV2Model.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2]  # noqa: E501
        if (self._configuration.client_side_validation and
                v_idm_elevation_status not in allowed_values):
            raise ValueError(
                "Invalid value for `v_idm_elevation_status` ({0}), must be one of {1}"  # noqa: E501
                .format(v_idm_elevation_status, allowed_values)
            )

        self._v_idm_elevation_status = v_idm_elevation_status

    @property
    def organization_group_id(self):
        """Gets the organization_group_id of this AdminV2Model.  # noqa: E501

        Gets or sets organization group ID.  # noqa: E501

        :return: The organization_group_id of this AdminV2Model.  # noqa: E501
        :rtype: int
        """
        return self._organization_group_id

    @organization_group_id.setter
    def organization_group_id(self, organization_group_id):
        """Sets the organization_group_id of this AdminV2Model.

        Gets or sets organization group ID.  # noqa: E501

        :param organization_group_id: The organization_group_id of this AdminV2Model.  # noqa: E501
        :type: int
        """

        self._organization_group_id = organization_group_id

    @property
    def organization_group_uuid(self):
        """Gets the organization_group_uuid of this AdminV2Model.  # noqa: E501

        Gets or sets organization group UUID.  # noqa: E501

        :return: The organization_group_uuid of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._organization_group_uuid

    @organization_group_uuid.setter
    def organization_group_uuid(self, organization_group_uuid):
        """Sets the organization_group_uuid of this AdminV2Model.

        Gets or sets organization group UUID.  # noqa: E501

        :param organization_group_uuid: The organization_group_uuid of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._organization_group_uuid = organization_group_uuid

    @property
    def id(self):
        """Gets the id of this AdminV2Model.  # noqa: E501

        Gets or sets identifier.  # noqa: E501

        :return: The id of this AdminV2Model.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdminV2Model.

        Gets or sets identifier.  # noqa: E501

        :param id: The id of this AdminV2Model.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def uuid(self):
        """Gets the uuid of this AdminV2Model.  # noqa: E501

        Gets or sets current objects UUID.  # noqa: E501

        :return: The uuid of this AdminV2Model.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this AdminV2Model.

        Gets or sets current objects UUID.  # noqa: E501

        :param uuid: The uuid of this AdminV2Model.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminV2Model, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminV2Model):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdminV2Model):
            return True

        return self.to_dict() != other.to_dict()
